### ISSUE TITLE
Did you plan to release the Fuzzer driver of JIGSAW?

### ISSUE THREAD

**Issue by Kenun99** [R-Fuzz/jigsaw#3]
I was wondering whether it is possible to let me access the fuzzer driver of JIGSAW.
As the paper said, JIGSAW is able to run Fuzzbench. I found FastGen from https://github.com/R-Fuzz/fastgen, which can use Z3 or JIGSAW as its solver. However, I didn't find the option to activate JIGSAW. Did you plan to release the hyper fuzzer driver of JIGSAW? Thank you.

**Comment by ChengyuSong** [comment]
fastgen includes a rust implementation of jigsaw, but it's no longer maintained. you can also try the new afl++ plugin https://github.com/R-Fuzz/symsan/tree/main/driver/aflpp
